[project]
name = "pymoto"
version = "0.0.0"
description = "A framework for experimenting with Kuramoto oscillator networks."
requires-python = ">=3.12"
dependencies = [
    "torch",
]

[project.optional-dependencies]
test = ["pytest", "coverage"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["pymoto"]

[tool.coverage.report]
show_missing = true
