name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pymoto
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package with test dependencies
        run: pip install -e ".[test]"

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
